# Generated by Django 2.1.2 on 2018-10-29 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_icon', models.ImageField(default='default_element.png', upload_to='elements_icons')),
                ('element_name', models.CharField(max_length=64)),
                ('element_description', models.TextField(blank=True, max_length=512, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('moderation', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('group_icon', models.ImageField(default='default_group.png', upload_to='groups_icons')),
                ('group_name', models.CharField(max_length=64)),
                ('group_description', models.TextField(blank=True, max_length=512, null=True)),
                ('parent_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='element',
            name='parent_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='groups.Group'),
        ),
    ]
